### ISSUE TITLE
Throttle calls to youtube

### ISSUE THREAD

**Issue by DeanWard** [currodev/Spotube#1]
When building the youtube playlist I see a lot of rejected calls :

{'status': 403, 'body': "<?xml version='1.0' encoding='UTF-8'?><errors><error><domain>yt:quota</domain><code>too_many_recent_calls</code></error></errors>", 'reason': 'Forbidden'}

**Comment by currodev** [comment]
Yes, I've the same problem, sometimes I've got a couple of them and another times I've got a lot of. I'm looking how to solve it.

**Comment by currodev** [comment]
Workaround:
recover command to add missing videos later

commit 488f85e11b59710afb85747b7c6b8afae03a7c6f
